### Get
GET http://localhost:3000/api/notas
### Get para contar
GET http://localhost:3000/api/notas/count
### Get for id
GET http://localhost:3000/api/notas/65ff377b27fcb511c0da9a2f
### Post 
POST http://localhost:3000/api/notas
Content-Type: application/json

{
    "title": "Probando",
    "autor": "Brandon",
    "content": "Hola mundo jeje",
    "important": true
}

### Put
PUT http://localhost:3000/api/notas/65ff3236b9fa3ecfd4f53632
Content-Type: application/json

{
    "title": "Todo bien",
    "content": "Hola mundo x2 jeje",
    "important": true   
}
### Delete
DELETE http://localhost:3000/api/notas/65ff3236b9fa3ecfd4f53632